Repository KaTeX/KaTeX, pull requests merged in 2018-08, with the labels that each got.

#1556 Sync support pages
  docs/support_table.md
  docs/supported.md
  website/pages/index.html
  website/static/css/custom.css
Labels: GH Review: review-needed

#1629 Fix line break and variable expansion in CHANGED variable
  .circleci/config.yml
Labels: bug

#1623 Fix copying options in auto render
  contrib/auto-render/auto-render.js
Labels: bug

#1637 make SourceLocation fields readonly
  src/SourceLocation.js
Labels: GH Review: review-needed

#1636 make all classes in domTree.js PascalCase and make them named exports
  .eslintrc
  dockers/screenshotter/screenshotter.js
  dockers/texcmp/texcmp.js
  katex.js
  src/buildCommon.js
  src/buildHTML.js
  src/delimiter.js
  src/domTree.js
  src/functions/color.js
  src/functions/href.js
  src/functions/htmlmathml.js
  src/functions/mathchoice.js
  src/functions/op.js
  src/functions/operatorname.js
  src/functions/phantom.js
  src/functions/sqrt.js
  src/functions/supsub.js
  src/mathMLTree.js
  src/stretchy.js
  src/tree.js
  test/helpers.js
Labels: GH Review: review-needed

#1653 Revert pkg.main to CommonJS (ES5) module and remove pkg.module field
  package.json
Labels: high priority

#1633 simplify combining chars
  src/buildCommon.js
  src/domTree.js
  src/functions/op.js
  src/functions/text.js
  src/functions/verb.js
  src/tree.js
Labels: GH Review: review-needed

#1680 Move to katex.org
  CONTRIBUTING.md
  README.md
  bower.json
  contrib/auto-render/README.md
  docs/font.md
  docs/support_table.md
  docs/supported.md
  release.sh
  website/core/Footer.js
  website/package.json
  website/pages/index.html
  website/siteConfig.js
  website/versioned_docs/version-0.10.0-rc.1/font.md
  website/versioned_docs/version-0.10.0-rc.1/support_table.md
  website/versioned_docs/version-0.10.0-rc.1/supported.md
Labels: GH Review: review-needed
