Repository KaTeX/KaTeX, pull requests merged in 2018-07, with the labels that each got.

#1474 AsciiMath: link to asciimath2tex
  README.md
Labels: documentation

#1454 \char character escaping and nicer MathML via \html@mathml
  src/ParseNode.js
  src/Parser.js
  src/functions.js
  src/functions/char.js
  src/functions/htmlmathml.js
  src/functions/mclass.js
  src/macros.js
  test/__snapshots__/mathml-spec.js.snap
  test/katex-spec.js
  test/mathml-spec.js
Labels: GH Review: review-needed

#1487 \@binrel command and refactor
  src/functions/font.js
  src/functions/mclass.js
  test/katex-spec.js
Labels: code cleanup, macro

#1336 Refactor test helpers
  test/Warning.js
  test/__snapshots__/katex-spec.js.snap
  test/errors-spec.js
  test/helpers.js
  test/katex-spec.js
  test/setup.js
  test/unicode-spec.js
Labels: GH Review: review-needed
