Repository KaTeX/KaTeX, pull requests merged in 2018-05, with the labels that each got.

#1232 Support some Unicode Mathematical Alphanumeric Symbols
  src/buildCommon.js
  src/buildMathML.js
  src/katex.less
  src/symbols.js
  src/wide-character.js
  test/katex-spec.js
  test/screenshotter/images/SurrogatePairs-chrome.png
  test/screenshotter/images/SurrogatePairs-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH Review: needs-revision

#1073 \copyright, \textregistered, \textcircled support
  src/functions/accent.js
  src/katex.less
  src/macros.js
  src/symbols.js
Labels: GH Review: review-needed

#1169 Stop throwing ParseError when throwOnError is false
  katex.js
  static/main.js
  test/__snapshots__/katex-spec.js.snap
  test/katex-spec.js
Labels: GH Review: review-needed

#1297 Update texcmp
  dockers/texcmp/Dockerfile
Labels: infrastructure

#1302 Document new error handling behavior (renderOnError)
  README.md
Labels: documentation

#1287 Line breaks for inline formulas
  src/buildCommon.js
  src/buildHTML.js
  src/domTree.js
  src/katex.less
  src/macros.js
  src/symbols.js
  test/katex-spec.js
  test/screenshotter/images/ArrayMode-chrome.png
  test/screenshotter/images/Baseline-chrome.png
  test/screenshotter/images/BoldSpacing-chrome.png
  test/screenshotter/images/BoldSymbol-chrome.png
  test/screenshotter/images/Cases-chrome.png
  test/screenshotter/images/ColorSpacing-chrome.png
  test/screenshotter/images/DeepFontSizing-chrome.png
  test/screenshotter/images/DisplayMode-chrome.png
  test/screenshotter/images/Gathered-chrome.png
  test/screenshotter/images/HorizontalBraces-chrome.png
  test/screenshotter/images/LeftRightListStyling-chrome.png
  test/screenshotter/images/LimitControls-chrome.png
  test/screenshotter/images/LineBreak-chrome.png
  test/screenshotter/images/LineBreak-firefox.png
  test/screenshotter/images/MathDefaultFonts-chrome.png
  test/screenshotter/images/MathOp-chrome.png
  test/screenshotter/images/NegativeSpace-chrome.png
  test/screenshotter/images/PrimeSpacing-chrome.png
  test/screenshotter/images/PrimeSuper-chrome.png
  test/screenshotter/images/Raisebox-chrome.png
  test/screenshotter/images/SizingBaseline-chrome.png
  test/screenshotter/images/SqrtRoot-chrome.png
  test/screenshotter/images/StyleSwitching-chrome.png
  test/screenshotter/images/SupSubOffsets-chrome.png
  test/screenshotter/ss_data.yaml
Labels: GH Review: needs-revision

#1305 Cleanup domTree.js to re-use code
  src/domTree.js
Labels: code cleanup

#1308 throwOnError documentation bug fix
  README.md
Labels: bug, documentation

#1278 Implement strict mode (replacing unicodeTextInMathMode)
  README.md
  package.json
  src/Parser.js
  src/Settings.js
  src/functions/kern.js
  static/main.js
  test/Warning.js
  test/katex-spec.js
  test/setup.js
  test/unicode-spec.js
Labels: GH Review: review-needed

#1198 Documenting String.raw
  README.md
Labels: GH Review: review-needed

#1318 Move test helpers into common modules
  package.json
  test/__snapshots__/katex-spec.js.snap
  test/errors-spec.js
  test/helpers.js
  test/katex-spec.js
  test/setup.js
  test/unicode-spec.js
Labels: infrastructure

#1338 Cleanup MathML <mrow>, <mtext>, <mn>
  src/buildMathML.js
  src/functions/delimsizing.js
  src/functions/genfrac.js
  src/functions/href.js
  src/functions/mathchoice.js
  src/functions/text.js
  test/__snapshots__/mathml-spec.js.snap
  test/mathml-spec.js
Labels: MathML

#1162 Fix lap vertical alignment.
  src/functions/lap.js
  test/screenshotter/images/Lap-chrome.png
  test/screenshotter/images/Lap-firefox.png
  test/screenshotter/images/Lap_alt-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH Review: needs-revision

#1348 \def support (and \gdef and \global\def)
  README.md
  katex.js
  src/MacroExpander.js
  src/Namespace.js
  src/Parser.js
  src/environments/array.js
  src/macros.js
  src/parseTree.js
  static/main.js
  test/helpers.js
  test/katex-spec.js
Labels: GH review: accepted

#1156 Rewrite spacing commands as macros
  src/buildCommon.js
  src/defineFunction.js
  src/functions.js
  src/functions/kern.js
  src/functions/mod.js
  src/functions/operatorname.js
  src/functions/symbolsSpacing.js
  src/katex.less
  src/macros.js
  src/mathMLTree.js
  src/symbols.js
  test/__snapshots__/mathml-spec.js.snap
  test/mathml-spec.js
  test/screenshotter/images/ArrayMode-chrome.png
  test/screenshotter/images/ArrayMode-firefox.png
  test/screenshotter/images/FractionTest-chrome.png
  test/screenshotter/images/LimitControls-chrome.png
  test/screenshotter/images/ModScript-chrome.png
  test/screenshotter/images/ModScript-firefox.png
  test/screenshotter/images/StyleSpacing-chrome.png
  test/screenshotter/images/StyleSpacing-firefox.png
Labels: GH review: accepted
