Repository KaTeX/KaTeX, pull requests merged in 2018-09, with the labels that each got.

#1687 Enable Greenkeeper on website/package.json
  greenkeeper.json
  website/package.json
Labels: GH Review: review-needed

#1683 Move to Netlify
  release.sh
  website/package.json
  website/static/_headers
  website/static/_redirects
  website/static/function-support.html
Labels: GH Review: review-needed

#1684 Add Flow types to CssStyle.
  src/domTree.js
Labels: GH review: accepted

#1688 Enable Algolia Docsearch (documentation search)
  website/siteConfig.js
Labels: GH review: accepted

#1640 extract makeVerb and some spacing functions from buildCommon
  src/buildCommon.js
  src/functions/symbolsSpacing.js
  src/functions/verb.js
Labels: GH review: accepted

#1658 Improve & fix CircleCI scripts
  .circleci/config.yml
Labels: GH Review: review-needed

#1697 chore(package): update file-loader to version 2.0.0
  package.json
  yarn.lock
Labels: GH Review: review-needed

#1710 Remove greenkeeper-lockfile
  .circleci/config.yml
  package.json
  yarn.lock
Labels: GH Review: review-needed

#1721 Fix tag positioning to live within katex-html parent
  src/katex.less
  test/screenshotter/images/Tag-chrome.png
  test/screenshotter/images/Tag-firefox.png
Labels: GH Review: review-needed

#1727 Including canvas rendering in libs
  docs/libs.md
Labels: GH review: accepted, documentation
