Repository KaTeX/KaTeX, pull requests merged in 2018-02, with the labels that each got.

#1161 Add a paragraph about injection safety
  README.md
Labels: documentation

#1111 Nested Math in Non-Default Text Fix
  src/Options.js
  src/buildCommon.js
  src/buildMathML.js
  src/functions/font.js
  src/functions/operatorname.js
  src/functions/styling.js
  src/functions/text.js
  test/__snapshots__/katex-spec.js.snap
  test/katex-spec.js
  test/screenshotter/images/TextWithMath-chrome.png
  test/screenshotter/images/TextWithMath-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH Review: needs-revision

#1117 unicodeTextInMathMode setting
  README.md
  src/Parser.js
  src/Settings.js
  src/symbols.js
  test/katex-spec.js
  test/mathml-spec.js
  test/unicode-spec.js
Labels: GH Review: review-needed
