Repository KaTeX/KaTeX, pull requests merged in 2018-06, with the labels that each got.

#1379 Fix ligatures vs. \tt
  src/Parser.js
  src/buildCommon.js
  src/buildMathML.js
  src/functions/symbolsOrd.js
  src/functions/text.js
  src/mathMLTree.js
  src/symbols.js
  test/__snapshots__/mathml-spec.js.snap
  test/mathml-spec.js
  test/screenshotter/images/DashesAndQuotes-chrome.png
  test/screenshotter/images/DashesAndQuotes-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH review: accepted

#1406 Support \widecheck
  src/functions/accent.js
  src/stretchy.js
  src/svgGeometry.js
  test/katex-spec.js
  test/screenshotter/images/StretchyAccent-chrome.png
  test/screenshotter/images/StretchyAccent-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH review: accepted

#1407 Support \hdashline
  src/environments/array.js
  src/katex.less
  test/__snapshots__/katex-spec.js.snap
  test/katex-spec.js
  test/screenshotter/images/Arrays-chrome.png
  test/screenshotter/images/Arrays-firefox.png
  test/screenshotter/images/Hline-chrome.png
  test/screenshotter/images/Hline-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH Review: review-needed

#1382 \newcommand, \renewcommand, \providecommand
  src/MacroExpander.js
  src/Namespace.js
  src/environments/array.js
  src/macros.js
  test/helpers.js
  test/katex-spec.js
  test/mathml-spec.js
  test/setup.js
  test/unicode-spec.js
Labels: GH review: accepted

#1408 Port buildHTML to @flow.
  src/buildHTML.js
  src/domTree.js
  src/functions/accent.js
  src/functions/delimsizing.js
  src/functions/supsub.js
  src/stretchy.js
  src/utils.js
Labels: GH Review: review-needed

#1269 [plugin system] Add a utility function (setFontMetrics) to extend builtin fontMetrics
  katex.js
  package-lock.json
  src/Options.js
  src/buildCommon.js
  src/buildMathML.js
  src/delimiter.js
  src/fontMetrics.js
  src/symbols.js
  test/__snapshots__/katex-spec.js.snap
  test/katex-spec.js
Labels: GH review: accepted

#1388 Automatic mrel/mbin spacing for \boldsymbol
  src/functions/font.js
  src/functions/mclass.js
  test/__snapshots__/katex-spec.js.snap
  test/__snapshots__/mathml-spec.js.snap
  test/katex-spec.js
  test/screenshotter/images/BoldSymbol-chrome.png
  test/screenshotter/images/BoldSymbol-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH Review: review-needed

#1425 Support \gdef in multiple equations in auto-render
  contrib/auto-render/README.md
  contrib/auto-render/auto-render.js
Labels: contrib

#1446 Expose dom tree
  katex.js
Labels: GH Review: review-needed

#1449 Phantom text
  src/functions/phantom.js
  test/screenshotter/images/Phantom-chrome.png
  test/screenshotter/images/Phantom-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH Review: review-needed, bug

#1440 Allow only allowed protocols in \href
  README.md
  src/Parser.js
  src/Settings.js
  test/katex-spec.js
Labels: GH Review: review-needed
