Repository KaTeX/KaTeX, pull requests merged in 2019-12, with the labels that each got.

#2161 Reword unicode test comments
  test/unicode-spec.js
Labels: code cleanup

#2082 Add HTML extension
  contrib/render-a11y-string/render-a11y-string.js
  docs/issues.md
  docs/options.md
  docs/support_table.md
  docs/supported.md
  src/Settings.js
  src/buildHTML.js
  src/functions.js
  src/functions/html.js
  src/parseNode.js
  test/__snapshots__/katex-spec.js.snap
  test/katex-spec.js
  test/screenshotter/images/HTML-chrome.png
  test/screenshotter/images/HTML-firefox.png
  test/screenshotter/ss_data.yaml
  test/screenshotter/test.html
  website/lib/remarkable-katex.js
Labels: GH Review: review-needed

#2135 Add \message, \errmessage, and \show for debugging
  src/macros.js
  test/katex-spec.js
Labels: GH review: accepted

#2138 Move \global and \def to functions
  CONTRIBUTING.md
  contrib/render-a11y-string/render-a11y-string.js
  src/Parser.js
  src/functions.js
  src/functions/def.js
  src/macros.js
  src/parseNode.js
  test/katex-spec.js
Labels: GH review: accepted, high priority

#2151 Minor symbols.js formatting changes
  src/symbols.js
Labels: GH Review: review-needed

#2162 Add bra-ket notation
  docs/support_table.md
  docs/supported.md
  src/macros.js
  test/katex-spec.js
Labels: GH Review: review-needed
