Repository KaTeX/KaTeX, pull requests merged in 2020-07, with the labels that each got.

#2153 Use babel-plugin-preval instead of own unicodeMake for unicodeSymbols
  .eslintrc
  babel.config.js
  dockers/screenshotter/screenshotter.js
  package.json
  src/Parser.js
  src/unicodeAccents.js
  src/unicodeMake.js
  src/unicodeSymbols.js
  yarn.lock
Labels: GH Review: review-needed

#2289 Document \def doesn't support delimiters (#2288)
  docs/supported.md
Labels: documentation

#1841 Reset to leftmost spacing mode after newline
  src/buildHTML.js
  test/__snapshots__/katex-spec.js.snap
Labels: GH Review: review-needed

#2294 Link to Netlify on front page
  website/pages/index.html
Labels: documentation

#2301 build(deps): update dependencies
  .eslintrc
  .flowconfig
  .gitignore
  contrib/auto-render/test/auto-render-spec.js
  contrib/render-a11y-string/render-a11y-string.js
  dockers/screenshotter/screenshotter.js
  package.json
  rollup.config.js
  src/Parser.js
  src/buildMathML.js
  src/defineEnvironment.js
  src/functions/environment.js
  src/functions/op.js
  src/parseNode.js
  test/__snapshots__/katex-spec.js.snap
  test/__snapshots__/mathml-spec.js.snap
  test/dup-spec.js
  test/errors-spec.js
  test/katex-spec.js
  test/mathml-spec.js
  test/setup.js
  test/unicode-spec.js
  webpack.common.js
  website/package.json
  website/siteConfig.js
  website/static/js/scrollspy.js
  website/yarn.lock
  yarn.lock
Labels: GH Review: review-needed

#2311 chore: enable GitHub Dependabot
  .github/dependabot.yml
Labels: GH Review: review-needed

#2332 Support MathML \big, \bigg, \Big, and \Bigg
  src/delimiter.js
  src/functions/delimsizing.js
  test/__snapshots__/mathml-spec.js.snap
  test/mathml-spec.js
Labels: GH review: accepted

#2183 Support {gather} and {gather*}
  docs/support_table.md
  docs/supported.md
  src/Settings.js
  src/buildHTML.js
  src/environments/array.js
  src/katex.less
  src/mathMLTree.js
  src/parseNode.js
  test/katex-spec.js
  test/screenshotter/images/Gather-chrome.png
  test/screenshotter/images/Gather-firefox.png
  test/screenshotter/ss_data.yaml
Labels: GH review: accepted
